name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # Use 'temurin' distribution
          java-version: '17'       # Specify Java 17

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/your-spring-boot-app .

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Push to Google Container Registry
        run: docker push gcr.io/${{ secrets.GCP_PROJECT }}/your-spring-boot-app

      - name: Deploy to Cloud Run
        run: gcloud run deploy your-spring-boot-app \
          --image gcr.io/${{ secrets.GCP_PROJECT }}/your-spring-boot-app \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
